---
- name: Playbook di TEST
  hosts: all
  become: yes

  tasks:
  - name: Copy file test /tmp with permissions
    ansible.builtin.copy:
      src: ./test.yml
      dest: /tmp/test.yml
      mode: '0644'

  - name: Add the user 'james' with a bash shell, appending the group 'adm' and 'cockpit-ws' to the user's groups
    ansible.builtin.user:
      name: james
      shell: /bin/bash
      comment: James Doe
      groups: adm,cockpit-ws
      uid: 1040
 
- name: SSH verification
  hosts: all
  become: yes

  tasks:
  - name: Ensure service ssh systemd is at the latest version
    ansible.builtin.apt:
      name: ssh
      state: latest

  - name: Ensure that service ssh systemd is started
    ansible.builtin.service:
      name: ssh
      state: started
