---
- hosts: kubernetes
  become: true
  gather_facts: false

  tasks:
    - name: Check kubelet service
        name: kubelet
        state: started
      register: kubelet_status
  
    - name: Check the status of sshd
        name: sshd
        state: started
      register: sshd_status

    - name: Check firewalld service
        name: firewalld
        state: started
      register: firewalld_status
