---
- name: Query Kubernetes Cluster for Metrics
  hosts: kubernetes
  connection: local
  gather_facts: false

  tasks:
    - name: Get list of all nodes
      kubernetes.core.k8s_info:
        kind: Node
      register: nodes_info

    - name: Get CPU and memory usage from all nodes
      kubernetes.core.k8s_info:
        api_version: v1beta1
        kind: NodeMetrics
      register: node_metrics

    - name: Display Node Status and Metrics
      ansible.builtin.debug:
        msg: |
          Node: {{ item.metadata.name }}
          Status: {{ 'Ready' in (item.status.conditions | selectattr('type', 'equalto', 'Ready') | map(attribute='status') | list) }}
          CPU Used: {{ (node_metrics.resources | selectattr('metadata.name', 'equalto', item.metadata.name) | first).usage.cpu }}
          Memory Used: {{ (node_metrics.resources | selectattr('metadata.name', 'equalto', item.metadata.name) | first).usage.memory }}
          Total CPU: {{ item.status.capacity.cpu }}
          Total Memory: {{ item.status.capacity.memory }}
          Total Ephemeral Storage: {{ item.status.capacity['ephemeral-storage'] }}
      loop: "{{ nodes_info.resources }}"
